### ISSUE TITLE
--snapshots-names 'M0_snap_.$.ka' seems to be ignored

### ISSUE THREAD

**Issue by hmedina** [jonathan-laurent/KaTie#1]
When calling the TQLe and specifying snapshot names, the generated files stick to the default naming scheme of `snapshot.%.json`. This remains the case even with option `--native-snapshots`.

For example, invoking:
``$ query -t M0.trace -q query.txt -o M0_tql.csv --native-snapshots --snapshots-names M0_snap_.$.ka'``
Produces files named `snapshot.0.json` through `snapshot.19.json`. File extension not withstanding, these snapshots are correctly written in native Kappa4 syntax.

As a consequence, when invoking in parallel the engine, the snapshots start a race to see who overwrites who... E.g. the below code produces an amalgam of 20 snapshots, instead of 100.
```
#! /usr/bin/parallel --shebang
query -t M0.trace -q query.txt -o M0_tql.csv --native-snapshots --snapshots-names 'M0_snap_.$.ka'
query -t M1.trace -q query.txt -o M1_tql.csv --native-snapshots --snapshots-names 'M1_snap_.$.ka'
query -t M2.trace -q query.txt -o M2_tql.csv --native-snapshots --snapshots-names 'M2_snap_.$.ka'
query -t M3.trace -q query.txt -o M3_tql.csv --native-snapshots --snapshots-names 'M3_snap_.$.ka'
query -t M4.trace -q query.txt -o M4_tql.csv --native-snapshots --snapshots-names 'M4_snap_.$.ka'
```

**Comment by jonathan-laurent** [comment]
You should use `%` instead of `$` as a placeholder in snapshot names formats.
I updated TQL so that you can get a clean error message when doing this mistake.

**Comment by hmedina** [comment]
The help options should also get updated to reflect this, see #2

**Comment by jonathan-laurent** [comment]
Thanks for the pull request. :-)
