### ISSUE TITLE
Time, floats, & hallucination

### ISSUE THREAD

**Issue by hmedina** [jonathan-laurent/KaTie#14]
(related to https://github.com/Kappa-Dev/KappaTools/issues/662)

On branch hmedina-dev, under tests/large/wnt-causal-fork (which currently requires a specific [KaTools branch](https://github.com/Kappa-Dev/KappaTools/tree/fulltimestampinsnapshots) )

KaTIE is reporting values for time that are not present in the raw JSON trace. Concretely, Cat id 211, which got degraded in the transition from `snap_Sfs_pre_42679.ka` to `snap_Sfs_pst_42680.ka`, corresponding to rule application 42680:

| 'id_cat' | 'deg_u_T' | 'deg_u_E' |
| -- | -- | -- |
| 211 | 21.949533940604098 | 42680 |

* KaTie reports, `21.949533940604098`
* `kasim-output/trace.json` does not contain that string
* `kasim-output/trace.json` contains `[-1,21.9495339406041,42680,null]`, for the "real event" in question, and
* `kasim-output/trace.json` contains `[-1,21.9495339406041,42679,null]` for the previous "real event"

It appears a 1e-13 got expanded to 0.98e-13

Is this a problem with the KaTools misreading the trace, or misreporting the value to KaTIE?

**Comment by jonathan-laurent** [comment]
I was previously using `%.17g` to format floats and changed to `Yojson.Basic.write_std_float`. Is it better now?

**Comment by hmedina** [comment]
Yes! Now it's passing, with no caveat for time approximation.
