### ISSUE TITLE
query name collisions

### ISSUE THREAD

**Issue by hmedina** [jonathan-laurent/KaTie#20]
When the query file specifies the same name for multiple queries, there is no error message. It is unclear if one overwrites the other, or if the result is some interlaced output.

For an example, see https://github.com/jonathan-laurent/KaTie/tree/query_name_collision/tests/errors/query_name_collision

An improvement would be to throw an error so the user can rename their queries; ideally a message with the line numbers of the repeating query names, e.g. `Error, same query name appears twice in [file] at lines [a] and [b]`

**Comment by jonathan-laurent** [comment]
Done.
