### ISSUE TITLE
Snapshot at T=0 is empty

### ISSUE THREAD

**Issue by hmedina** [jonathan-laurent/KaTie#3]
A query like this:
```
match e every 10 seconds
do { snapshot[.e] }
```
Will produce snapshots of a trace every 10 or so simulation seconds. The very first snapshot (i.e. `snapshot.0.ka`) will be empty, even if the had non-zero initial amounts of stuff.

For example, this model:
```
%var: 'γf' 1.0e-4
%var: 'γu' 1.0e-2
%var: 'γ-0' 1.0e-1
%var: 'init' 1000
%agent: X(a,b)
'r0' X(a[.]),X(b[.]) <-> X(a[0]),X(b[0]) @ 'γf' {'γu'}, 'γ-0'
%init: 'init' X()

%obs: 'X1' |X(a,b)|
%obs: 'b0' |X(a[0]),X(b[0])|
```
With the above mentioned query will produce the following `snapshot.0.ka`.
```
// Snapshot [Event: 0]
%def: "T0" "0"




```
Is the TQLe trying to dump the snapshot before the intro events? Or is it only aware of events, ignoring initial conditions (e.g. an agent that has not participated in any event, but was introduced at initialization, would not be printed in the snapshot)?

**Comment by jonathan-laurent** [comment]
What happens is that a JSON trace starts with a series of special INIT events that setup the initial mixture. Your query matches the first INIT event, before which the mixture is empty.

**Comment by jonathan-laurent** [comment]
I just changed the default behavior of the TQL to skip initial events but I think this may not be desirable in other circumstances. Ultimately, Ill just add an option.

**Comment by hmedina** [comment]
I understand we use a special set of events to introduce the very first state of the mixture, but from the abstract perspective, isn't that purely an implementation artifact? Or is there a theosophical reason why there are two types of events, those that construct the world, and those that modify it? If so, you may have to think of having a language for analyzing the former class, seeing as the TQL is aimed at the latter kind :P

Anyhow, it works now and I'm not getting bugged down by empty snapshots :D

**Comment by jonathan-laurent** [comment]
Even from the abstract perspective, one may argue that it is useful to have explicit initialization events. For example, with such an event, there is always a direct cause of a site being in some state at some point in time (possibly an init event). Without initialization events, this isn't true anymore. 

To be even more concrete, let's consider the following query, which we can use to measure the average time needed by a substrate to get phosphorylated:
```
match p:[| S(x{/p}) |]
and last u:[| S{/u} |] before p
do { time[p] - time[u] }
```
Evaluating this query yields possibly very different results depending of whether or not you consider initialization events.

**Comment by hmedina** [comment]
True, whether or not you consider them will change the result. I can see the argument going for:
-I care about all events
-I care only about rule-events

What happens if I start the simulation using the `continue` mode and seeding with a snapshot, rather than inits? The inits default to default values, whereas the snapshot is explicit. Would the TQLe match as events what is in the seeding-snapshot? For example, given a signature `%agent: A(s{s p})`, and a snapshot containing `A(s{p})`, would there be an "phosphorylation init event"?
