### ISSUE TITLE
Error: Unbound record field Data.snapshot_file

### ISSUE THREAD

**Issue by hmedina** [jonathan-laurent/KaTie#5]
Trying to re-build the TQL engine after KaSim updates, I'm running into the below error:

```
~/Kappa-TQL$ make
ocamlbuild -use-ocamlfind main.native
+ ocamlfind ocamlopt -c -g -bin-annot -safe-string -open Kappa_generic_toolset -open Kappa_mixtures -open Kappa_terms -open Kappa_runtime -package kappa-library.runtime -package biniou -I src -o src/measures.cmx src/measures.ml
File "src/measures.ml", line 57, characters 8-26:
57 |         Data.snapshot_file = file ;
             ^^^^^^^^^^^^^^^^^^
Error: Unbound record field Data.snapshot_file
Hint: Did you mean snapshot_time?
Command exited with code 2.
Compilation unsuccessful after building 56 targets (0 cached) in 00:00:06.
make: *** [Makefile:4: all] Error 10
```

https://github.com/jonathan-laurent/Kappa-TQL/blob/502f7e1b046129af0374452ed694c4171c2e8c74/src/measures.ml#L57

**Comment by jonathan-laurent** [comment]
Nice to hear from you Hector!
I'll be looking at this in the next few days.

More generally, I think there is a case to be made that the TQL should be included in the main KaSim repo. This way, it won't get broken at each major update.

**Comment by hmedina** [comment]
Hi Jonathan! I think it would be perfectly acceptable for the TQLe to be one of the agents in the Kappa Tools umbrella, like the ODE generator (KaDe), static analyzer (KaSa) or the story thing (KaStor). Replace the "query" for an "inquiry", and you're halfway to a pronounceable acronym! Perhaps the Kappa Trace Inquiry Engine (KaTie) ?


FYI, I'm running into issues compiling KaSim (https://github.com/Kappa-Dev/KappaTools/issues/644), so I'll be taking a closer look at its github actions file in the coming days...

**Comment by jonathan-laurent** [comment]
I just pushed a fix and switched the build system to dune in passing. Enjoy!
