### ISSUE TITLE
Dune build - growing pains

### ISSUE THREAD

**Issue by hmedina** [jonathan-laurent/KaTie#6]
Although it compiles, I can't get the executable to do much. Invoking it does not print usage:
```
$ ./query
$
```
Running the built-in tests also does not produce an `out` folder, as per the `tests/catphos/Makefile`, nor does it produce any of the old standard outputs (e.g. "Queries successfully compiled.", `main.ml`, line 83), even though the `t.json` and `query` files are present.
```
$ make test
dune build src/query.exe
mv _build/default/src/query.exe query
cd tests/catphos ; make
make[1]: Entering directory '/Kappa-TQL/tests/catphos'
KaSim --no-log catphos.ka -trace t.json
Parsing catphos.ka...
done
+ simulation parameters
+ Sanity checks
+ Compiling...
+ Building initial simulation conditions...
         -variable declarations
         -rules
         -interventions
         -observables
         -update_domain construction
         12 (sub)observables 6 navigation steps
         -initial conditions
+ Self seeding...
+ Building initial state (7000 agents)
Done
+ Command line to rerun is: 'KaSim' '--no-log' 'catphos.ka' '-trace' 't.json' -seed 131901439
14.07 time units in 96827 events
Simulation ended
../../query -t t.json -q query \
--native-snapshots --snapshots-names "snapshot.%.ka" \
--output-directory out \
--debug
make[1]: Leaving directory '/Kappa-TQL/tests/catphos'
```

Inspecting the `src/dune` file, the target is listed as `name query`, which points to query.ml, which is not the [main entry point of the executable](https://dune.readthedocs.io/en/stable/dune-files.html#executable-1). Switching it to `main` instead, shows a litany of other errors, including problems finding the lexer and parser.

Adding the following stanzas to the `src/dune` file (and bumping the Dune language requirement to 2.0 for Menhir type-inference support)
```
(ocamllex query_lexer)
(menhir
  (modules query_parser))
```
Allows dune to find them and advance the compilation. However errors remain. Besides `unused-value-delcarations`, the errors remaining are of the `unbound module` class:
```
$ make
dune build src/main.exe
File "src/streaming.mli", line 2, characters 19-31:
2 |   previous_state : Replay.state;
                       ^^^^^^^^^^^^
Error: Unbound module Replay
File "src/history.ml", line 116, characters 4-10:
116 | let test_1 () =
          ^^^^^^
Error (warning 32 [unused-value-declaration]): unused value test_1.
File "src/expr_eval.ml", line 43, characters 8-21:
43 | let rec compare_lists cmp xs ys =
             ^^^^^^^^^^^^^
Error (warning 32 [unused-value-declaration]): unused value compare_lists.
File "src/expr_eval.ml", line 90, characters 33-35:
90 |     | (Binop (lhs_e, op, rhs_e), ty) ->
                                      ^^
Error (warning 27 [unused-var-strict]): unused variable ty.
File "src/expr_eval.ml", line 97, characters 28-30:
97 |     | (Unop (Unop op, arg), ty) -> map_option op (eval_expr read_measure read_id arg)
                                 ^^
Error (warning 27 [unused-var-strict]): unused variable ty.
File "src/expr_eval.ml", line 98, characters 37-39:
98 |     | (Unop (Count_agents ags, arg), ty) ->
                                          ^^
Error (warning 27 [unused-var-strict]): unused variable ty.
File "src/main.ml", line 79, characters 23-50:
79 |     let (uuid,model) = Trace.get_headers_from_file !trace_file in
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound module Trace
File "src/query_compile.ml", line 264, characters 4-12:
264 | let expr_not i = if i = 0 then 1 else 0
          ^^^^^^^^
Error (warning 32 [unused-value-declaration]): unused value expr_not.
File "src/query_compile.ml", line 268, characters 4-13:
268 | let expr_body = fst
          ^^^^^^^^^
Error (warning 32 [unused-value-declaration]): unused value expr_body.
File "src/query_compile.ml", line 291, characters 4-15:
291 | let int_of_bool = function
          ^^^^^^^^^^^
Error (warning 32 [unused-value-declaration]): unused value int_of_bool.
make: *** [Makefile:6: build] Error 1
```
I've only found one instance of `get_headers_from_file` in the entire code, so I don't know where this `Trace` object would be defined. Same for `Replay`.

**Comment by jonathan-laurent** [comment]
Sorry, it looked like I took the OCaml motto _"if it compiles it must work"_ a bit too literally!

Your diagnose is correct and you were only missing a final step, which was to add the "-open Kappa_runtime" flag.

Also, a `~raw` argument was added to the Snapshot related functions. I passed `true` but please tell me if this was the wrong choice (documentation was never a strength of KaSim's codebase).

**Comment by hmedina** [comment]
Great, the next issue is with `biniou`; I'm seeing you're still using `Bi_outbuf` in `measures.ml`, however `Yojson` no longer contains `biniou`, so having up-to-date `Yojson` in the system would require declaring the `biniou` package as a library dependency. The rest of the Kappa Tools got rid of `biniou` in https://github.com/Kappa-Dev/KappaTools/commit/0bd8ec9df036ac3600194b651840811a82f4edc2

I'll tweak that and make a pull request

**Comment by hmedina** [comment]
Done, see https://github.com/jonathan-laurent/Kappa-TQL/pull/7

As for the snapshots, I think this was a right choice. Passing that as `true` means snapshots are written in "expanded" format with their unique agent identifier:
```
%init: 1 x0:A()
%init: 1 x1:A()
%init: 1 x2:A()
```
instead of the "abridged" format that has no such identifiers:
```
%init: 3 A()
```

Since these "abridged" snapshots have less information, they should not be the sole possible behavior. Ideally though, this would be an option set somewhere by the user.
