### ISSUE TITLE
should `match e:{ +s:S(x{u}) }` be a syntactic error?

### ISSUE THREAD

**Issue by hmedina** [jonathan-laurent/KaTie#9]
From the test suite:
```
// WARNING: this one is tricky
// The tests are performed on the state BEFORE the rule is applied
// Here, the agent S does not exist yet when the x{u} test is performed.
query 'create_S_warn__matches_0.csv'
match e:{ +s:S(x{u}) }
return 1
```

At first glance, I would have thought the query would read like "match the creation of an agent `S` with a site `x` and an internal state `u` and assign it the label `s`".

However, it seems to actually read "match a site `x` with internal state `u` in a non-existent agent `S`, that gets created as part of this rule, and assign the agent the label `s`"

Is this reading correct? If so, it seems the query is not possible to satisfy, ever. Should this be flagged to the user as a syntactic error?

I.e. all matches for agent creation for which the agent signature contains non-operations, can never be satisfied?

**Comment by jonathan-laurent** [comment]
You are correct about the current semantics and also correct about it being quite useless.
I'll change the behavior to match what you expect.
The new syntax restriction will be: you cannot have site modification syntax within an agent that is created or deleted.

**Comment by hmedina** [comment]
That seems sensible. Both for agent deletion as well as for agent creation, KaSim does not allow operations (neither internal state, nor bond state) if the agent is being created/deleted.

Assuming the following toy model:
```
%agent: Bob(s{a, b})
'r1' Bob()+ @ 1
'r2' Bob(s{b})+ @ 1
'r3' Bob(s[1])+, Bob(s[1])+ @ 1
```

`match e:{+b:Bob(s{a})}` would match firings of `r1`
`match e:{+b:Bob(s{b})}` would match firings of `r2`
`match e:{+b:Bob(s[_])}` would match firings of `r3`, twice?

**Comment by jonathan-laurent** [comment]
I implemented the change you suggested. Everything makes much more sense now indeed.
You can look at the tests I added and also contribute your own.

Regarding your example, you are correct. The third query would be considered ambiguous by the current engine though, although we could make it supported in the future. More details to come in the documentation.

**Comment by jonathan-laurent** [comment]
**Update:** I removed the rigidity restriction so the third query should behave like you said indeed.

**Comment by jonathan-laurent** [comment]
@hmedina I added tests in accordance with your prediction in 2e71b41.

**Comment by hmedina** [comment]
Great, now that I understand how to avoid the snapshots-invalid-traces bug in https://github.com/Kappa-Dev/KappaTools/issues/656 I should be able to do manual cross-validation between KaSim and KaTie
